name: Go Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Install dependencies
      run: go test $(go list ./... | grep -v tools)

    - name: Run tests
      run: go test $(go list ./... | grep -v tools)
